# For more information about the configurations used
# in this file, please see the Travis CI documentation.
#
# https://docs.travis-ci.com

after_success:
  - npm run travis-update

env:
  global:
    - secure: "PanSWDk8u1QmoKYVrvn6pN8NvlE0EpUE86PcwC2vhu2s6feN9NKvtDqYXlxA5SwRED85MvXDbn+HJaSYo42q4gXczrAyQHOgC+P53/uSNn87f0NEaxdpDOZ4rDY6mVMekruyIGuCXqtmOpAN9khzchVQUJTwLp2895+YhehodWAasvFEFjo1HIfnE0anc8gU+e5KWNx9oepS6oyGzowbzhTD+AdDiTS4yPD58LJBr5j5cghaanpAVs7OCR898ER3zggYiPeYKULJNEZu1KB6JSGDtpTlZR+tkiSrDkoOEmOjG8/Zr3ZOo8Jwtumodg1TMWnuvlEzmzVbslON7WerxSBDV4f8IfyPtaz7DGMF406FPONyZqJTum08luu3OrBBEoaPXHrRm8yUyJ3Wlol6ra5uPDCSS7KqM/Ll/sxGYkxFWrPBGfQQive8IkqpsYDN4JirAh0PMlEsmeOKb/k39wFfx/NhgzhRFIXW3I24R1CDIPgeiBNK7l71Uv6XxaXXFR821zHhWQ9gJilrmreJTf2uDWKxQkLJ9DuY1ba0Z07EbDtgr6qw11b2ZmaVaBw6Uw8JqAmSXIvA7IMUgpl6UVfx4DLf1o+fQ3PfbzmGIVYq8VA+rEa9Kb6dqJOuZujtA8Ir0cQXNKp9tPmmkKipjfLZmkzCz0U/zjtm9pOgQFY="

language: node_js

dist: trusty

node_js:
  - node

notifications:
  email:
    on_failure: always
    on_success: never
