axe:
  logo:
    name: "axe"
    url: "/images/logos/axe.png"
    alt: "aXe"
  link: "https://github.com/dequelabs/axe-core"
ssllabs:
  logo:
    name: "ssllabs"
    url: "/images/logos/qualys-ssl-labs-logo.png"
    alt: "Qualys SSL Labs"
  details: true
  link: "https://www.ssllabs.com/ssltest/analyze.html?d=%URL%"
no-vulnerable-javascript-libraries:
  logo:
    name: "snyk"
    url: "/images/logos/snyk.svg"
    alt: "snyk"
  link: "https://snyk.io/vuln/"
cloudinary:
  logo:
    name: "cloudinary"
    url: "/images/logos/cloudinary_logo_for_white_bg.svg"
    alt: "Cloudinary"
  details: true
  link: "https://webspeedtest.cloudinary.com"
